import java.util.Random;
public class RandomArray {

	static void convert(int[] arr) 
	{
		Random r = new Random();
		for(int i=0;i<arr.length;i++)
		{
			int index=r.nextInt(arr.length);//generates indexes from 0 to arr.length-1
			//swapping value at i and value at index ,which is generated by random class
			int temp=arr[i];
			arr[i]=arr[index];
			arr[index]=temp;
		}
		for(int ele:arr)
		{
			System.out.print(ele+" ");
		}
	}
	public static void main(String[] args) 
	{
		int[] arr = {1,2,3,4,5,6,7};
		convert(arr);
	}

	

}
